### ISSUE TITLE
Parameters of `BertOnlyMLMHead` missing in `monologg/kobert`

### ISSUE THREAD

**Issue by jzbjyb** [monologg/DistilKoBERT#4]
Thanks for releasing the KoBERT model! However, I found that the parameters of `BertOnlyMLMHead` layer might be missing in the `monologg/kobert` model, which I think is a common issue that I also found in released BERT models for others languages, like [Greek](https://github.com/nlpaueb/greek-bert/issues/1) and [Russian](https://github.com/deepmipt/DeepPavlov/issues/1148).
To reproduce this issue:
```python
from transformers import *
m1 = AutoModelWithLMHead.from_pretrained('monologg/kobert')
print(m1.cls.predictions.transform.dense.weight)
m2 = AutoModelWithLMHead.from_pretrained('monologg/kobert')
print(m2.cls.predictions.transform.dense.weight)  # different from m1
```
Is it possible to upload the pretrained model with the missing parameters (either in huggingface's `transformers` or providing a link to the original tf checkpoint)?

**Comment by monologg** [comment]
Hi:) Thanks for reporting this issue.

Actually `KoBERT` isn't originally owned by me. (Original repo -> [SKTBrain KoBERT](https://github.com/SKTBrain/KoBERT)) This one is a ported version for `transformers` library. 

I've also noticed this issue when I first made this ported version. So I've made `monologg/kobert-lm`, which is retrained with my own corpus for 1 epoch, with the initialized parameter of `monologg/kobert`

----

> Is it possible to upload the pretrained model with the missing parameters (either in huggingface's `transformers` or providing a link to the original tf checkpoint)?

I'll check this one with original KoBERT owner:)

**Comment by jzbjyb** [comment]
I see. Thanks for the clarification! I will use `monologg/kobert-lm` for now and check later if the original KoBERT owner can fix this issue.
